language: node_js
node_js: 
  - "stable"
services:
  - mongodb
before_script:
  - sleep 15
  - mongo test_DB --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
cache: npm
script: 
  - npm run test
notifications: 
  email: false
after_success:
  - npm run coverage
