export const FacebookProfile = {
  id: '2947127098683344',
  username: undefined,
  displayName: undefined,
  name: {
    familyName: 'Holla',
    givenName: 'Gilla',
    middleName: 'Mundo',
  },
  gender: undefined,
  profileUrl: undefined,
  emails: [{ value: 'ben.erick@rocketmail.com' }],
  provider: 'facebook',
  _raw: '{"id":"2947127098683344","email":"holla\\u0040rocketmail.com","first_name":"Holla","last_name":"Gilla","middle_name":"Mundo"}',
  _json: {
    id: '2947127098683344',
    email: 'holla.erick@rocketmail.com',
    first_name: 'Holla',
    last_name: 'Gilla',
    middle_name: 'Mundo',
  },
};

export const GoogleProfile = {
  id: '105458063876592277316',
  displayName: 'Holla Eric',
  name: { familyName: 'Eric', givenName: 'holla' },
  emails: [{ value: 'holla69@gmail.com', verified: true }],
  photos: [
    {
      value: 'https://lh3.googleusercontent.com/a-/AOh14GgZ__rY5cCKljSo_O9YdUjp7lRah2mTqqOKfGmv',
    },
  ],
  provider: 'google',
  _raw: '{\n'
    + '  "sub": "105458063876592277316",\n'
    + '  "name": "holla Eric",\n'
    + '  "given_name": "holla",\n'
    + '  "family_name": "Eric",\n'
    + '  "picture": "https://lh3.googleusercontent.com/a-/AOh14GgZ__rY5cCKljSo_O9YdUjp7lRah2mTqqOKfGmv",\n'
    + '  "email": "holla69@gmail.com",\n'
    + '  "email_verified": true,\n'
    + '  "locale": "en"\n'
    + '}',
  _json: {
    sub: '105458063876592277316',
    name: 'Niyongabo Eric',
    given_name: 'Niyongabo',
    family_name: 'Eric',
    picture: 'https://lh3.googleusercontent.com/a-/AOh14GgZ__rY5cCKljSo_O9YdUjp7lRah2mTqqOKfGmv',
    email: 'holla69@gmail.com',
    email_verified: true,
    locale: 'en',
  },
};
export const TwitterProfile = {
  id: '779313652344221699',
  username: 'holla69',
  displayName: 'holla Eric',
  emails: [{ value: 'holla69@gmail.com' }],
  photos: [
    {
      value: 'https://pbs.twimg.com/profile_images/779994062627667968/KXvvM0CA_normal.jpg',
    },
  ],
  provider: 'twitter',
  _raw: '{"id":779313652344221699,"id_str":"779313652344221699","name":"Niyongabo Eric","screen_name":"niyongaboeric69","location":"Rwanda","description":"","url":null,"entities":{"description":{"urls":[]}},"protected":false,"followers_count":79,"friends_count":156,"listed_count":3,"created_at":"Fri Sep 23 13:37:08 +0000 2016","favourites_count":134,"utc_offset":null,"time_zone":null,"geo_enabled":false,"verified":false,"statuses_count":380,"lang":null,"status":{"created_at":"Sun Mar 01 16:19:16 +0000 2020","id":1234151224964001792,"id_str":"1234151224964001792","text":"What limits us from achieving our dream? I think it is imagination and courage. I believe the difference between su\\u2026 https:\\/\\/t.co\\/dYmKo56dCc","truncated":true,"entities":{"hashtags":[],"symbols":[],"user_mentions":[],"urls":[{"url":"https:\\/\\/t.co\\/dYmKo56dCc","expanded_url":"https:\\/\\/twitter.com\\/i\\/web\\/status\\/1234151224964001792","display_url":"twitter.com\\/i\\/web\\/status\\/1\\u2026","indices":[117,140]}]},"source":"\\u003ca href=\\"https:\\/\\/mobile.twitter.com\\" rel=\\"nofollow\\"\\u003eTwitter Web App\\u003c\\/a\\u003e","in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"geo":null,"coordinates":null,"place":null,"contributors":null,"is_quote_status":false,"retweet_count":0,"favorite_count":2,"favorited":true,"retweeted":false,"possibly_sensitive":false,"lang":"en"},"contributors_enabled":false,"is_translator":false,"is_translation_enabled":false,"profile_background_color":"000000","profile_background_image_url":"http:\\/\\/abs.twimg.com\\/images\\/themes\\/theme1\\/bg.png","profile_background_image_url_https":"https:\\/\\/abs.twimg.com\\/images\\/themes\\/theme1\\/bg.png","profile_background_tile":false,"profile_image_url":"http:\\/\\/pbs.twimg.com\\/profile_images\\/779994062627667968\\/KXvvM0CA_normal.jpg","profile_image_url_https":"https:\\/\\/pbs.twimg.com\\/profile_images\\/779994062627667968\\/KXvvM0CA_normal.jpg","profile_banner_url":"https:\\/\\/pbs.twimg.com\\/profile_banners\\/779313652344221699\\/1474799782","profile_link_color":"19CF86","profile_sidebar_border_color":"000000","profile_sidebar_fill_color":"000000","profile_text_color":"000000","profile_use_background_image":false,"has_extended_profile":true,"default_profile":false,"default_profile_image":false,"following":false,"follow_request_sent":false,"notifications":false,"translator_type":"none","suspended":false,"needs_phone_verification":false,"email":"niyongaboeric69@gmail.com"}',
  _json: {
    id: 779313652344221700,
    id_str: '779313652344221699',
    name: 'holla Eric',
    screen_name: 'holl69',
    location: 'Rwanda',
    description: '',
    url: null,
    entities: { description: [Object] },
    protected: false,
    followers_count: 79,
    friends_count: 156,
    listed_count: 3,
    created_at: 'Fri Sep 23 13:37:08 +0000 2016',
    favourites_count: 134,
    utc_offset: null,
    time_zone: null,
    geo_enabled: false,
    verified: false,
    statuses_count: 380,
    lang: null,
    status: {
      created_at: 'Sun Mar 01 16:19:16 +0000 2020',
      id: 1234151224964001800,
      id_str: '1234151224964001792',
      text: 'What limits us from achieving our dream? I think it is imagination and courage. I believe the difference between su… https://t.co/dYmKo56dCc',
      truncated: true,
      entities: [Object],
      source: '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
      in_reply_to_status_id: null,
      in_reply_to_status_id_str: null,
      in_reply_to_user_id: null,
      in_reply_to_user_id_str: null,
      in_reply_to_screen_name: null,
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      retweet_count: 0,
      favorite_count: 2,
      favorited: true,
      retweeted: false,
      possibly_sensitive: false,
      lang: 'en',
    },
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: '000000',
    profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_tile: false,
    profile_image_url: 'http://pbs.twimg.com/profile_images/779994062627667968/KXvvM0CA_normal.jpg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/779994062627667968/KXvvM0CA_normal.jpg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/779313652344221699/1474799782',
    profile_link_color: '19CF86',
    profile_sidebar_border_color: '000000',
    profile_sidebar_fill_color: '000000',
    profile_text_color: '000000',
    profile_use_background_image: false,
    has_extended_profile: true,
    default_profile: false,
    default_profile_image: false,
    following: false,
    follow_request_sent: false,
    notifications: false,
    translator_type: 'none',
    suspended: false,
    needs_phone_verification: false,
    email: 'holla69@gmail.com',
  },
  _accessLevel: 'read',
};

export const GithubProfile = {
  id: '33821734',
  displayName: null,
  username: 'holla',
  profileUrl: 'https://github.com/NiyongaboEric',
  photos: [
    { value: 'https://avatars1.githubusercontent.com/u/33821734?v=4' },
  ],
  provider: 'github',
  _raw: '{"login":"NiyongaboEric","id":33821734,"node_id":"MDQ6VXNlcjMzODIxNzM0","avatar_url":"https://avatars1.githubusercontent.com/u/33821734?v=4","gravatar_id":"","url":"https://api.github.com/users/NiyongaboEric","html_url":"https://github.com/NiyongaboEric","followers_url":"https://api.github.com/users/NiyongaboEric/followers","following_url":"https://api.github.com/users/NiyongaboEric/following{/other_user}","gists_url":"https://api.github.com/users/NiyongaboEric/gists{/gist_id}","starred_url":"https://api.github.com/users/NiyongaboEric/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/NiyongaboEric/subscriptions","organizations_url":"https://api.github.com/users/NiyongaboEric/orgs","repos_url":"https://api.github.com/users/NiyongaboEric/repos","events_url":"https://api.github.com/users/NiyongaboEric/events{/privacy}","received_events_url":"https://api.github.com/users/NiyongaboEric/received_events","type":"User","site_admin":false,"name":null,"company":"Andela Kigali","blog":"www.andela.com","location":"Rwanda","email":null,"hireable":null,"bio":"Fullstack developer","public_repos":27,"public_gists":0,"followers":4,"following":14,"created_at":"2017-11-20T05:20:21Z","updated_at":"2020-03-01T13:16:22Z"}',
  _json: {
    login: 'NiyongaboEric',
    id: 33821734,
    node_id: 'MDQ6VXNlcjMzODIxNzM0',
    avatar_url: 'https://avatars1.githubusercontent.com/u/33821734?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/NiyongaboEric',
    html_url: 'https://github.com/NiyongaboEric',
    followers_url: 'https://api.github.com/users/NiyongaboEric/followers',
    following_url: 'https://api.github.com/users/NiyongaboEric/following{/other_user}',
    gists_url: 'https://api.github.com/users/NiyongaboEric/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/NiyongaboEric/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/NiyongaboEric/subscriptions',
    organizations_url: 'https://api.github.com/users/NiyongaboEric/orgs',
    repos_url: 'https://api.github.com/users/NiyongaboEric/repos',
    events_url: 'https://api.github.com/users/NiyongaboEric/events{/privacy}',
    received_events_url: 'https://api.github.com/users/NiyongaboEric/received_events',
    type: 'User',
    site_admin: false,
    name: null,
    company: 'Andela Kigali',
    blog: 'www.andela.com',
    location: 'Rwanda',
    email: null,
    hireable: null,
    bio: 'Fullstack developer',
    public_repos: 27,
    public_gists: 0,
    followers: 4,
    following: 14,
    created_at: '2017-11-20T05:20:21Z',
    updated_at: '2020-03-01T13:16:22Z',
  },
  emails: [
    {
      value: 'holla69@gmail.com',
      primary: true,
      verified: true,
    },
    {
      value: '33821734+NiyongaboEric@users.noreply.github.com',
      primary: false,
      verified: true,
    },
  ],
};
